### ISSUE TITLE
Block G and other traders button issue

### ISSUE THREAD

**Issue by theparksilford** [theparksilford/Issues#30]
### Property Details

Block G

### Type of problem?

Repair

### Since when this issue started?

Few months 

### Issue Description?

Many blocks including Block G have traders button which let anyone in at any time. This allows people to come in and smoke drugs or cause general nuisance. 
please get this fixed, starting with Block G. We should check other blocks too. 

### Logged By

Directors

**Comment by theparksilford** [comment]
No just checked and it still opens to all. It should have a timing but it works 24/7

**Comment by theparksilford** [comment]
Please provide the update. This is still not fixed.

**Comment by theparksilford** [comment]
Please update. This is taking forever. We need to get this door fixed.

**Comment by jeremydoran** [comment]
This should now be resolved, please can some one check this later this evening and report back if this is not the case.

**Comment by theparksilford** [comment]
I checked just now. It’s Sunday 3pm. Should it work? I can press and entered. Will try tomorrow as well.

**Comment by jeremydoran** [comment]
Please try again after 6 o'clock. 

I have asked the contractor to attend again to change the timings and also to check the settings.

**Comment by theparksilford** [comment]
This is still letting me in at 8pm. Surely this is not fixed. Please get this fixed tomorrow as we have enough of people barging in without any regards.

**Comment by jeremydoran** [comment]
Thanks for letting me know, I have asked the contractor to attend to this tomorrow.

**Comment by theparksilford** [comment]
Block G traders button appears to be working. I have asked the residents to confirm it.

**Comment by jeremydoran** [comment]
The contractor has advised me yesterday that this has now been resolved.

**Comment by theparksilford** [comment]
For block G,looks like the trade button let people in on Saturday. Sunday I checked and it’s fine. 
also what’s the plan for other blocks? Could you update the list here and when it will be looked at?

**Comment by jeremydoran** [comment]
Please could you advise if the doors works only between the hours of 6am - 11am on either Saturday or Sunday?

**Comment by jeremydoran** [comment]
For block G only?

**Comment by jeremydoran** [comment]
The doors that need the trade button timer set correctly or replaced are blocks:
1-15
68-78
88-78
54-66
30-40
17-27 & the door does not close correctly
181-195
165-179  

I have asked the contractor to attend to this, it might be a case of an adjustment to the time clock or if the time clock is no longer working correctly then this may need to be changed. 

I will let know when I have a date back from the contractor.

**Comment by theparksilford** [comment]
For Block G, During weekdays it seems be working fine. Saturday 1:30pm it was tested and was letting people in. Sunday 3pm it was working fine. So could be Saturday not set correctly.

**Comment by jeremydoran** [comment]
Okay I will advise the contractor that attended to this recently to adjust this.

**Comment by jeremydoran** [comment]
This has now been resolved and all the time clock have now been adjusted and work correctly.
